### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by johnbendi** [alexisvincent/systemjs-config-builder#17]
I followed the brief installation directions:

1. yarn global add systemjs-tools
2. yarn add systemjs-nodelibs
3. systemjs config

Then I got:

```
Unhandled rejection TypeError: Cannot read property 'name' of null
    at ~/.config/yarn/global/node_modules/systemjs-config-builder/dist/index.js:126:42
    at Array.forEach (native)
    at ~/.config/yarn/global/node_modules/systemjs-config-builder/dist/index.js:125:25
    at tryCatcher (~/.config/yarn/global/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (~/.config/yarn/global/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (~/.config/yarn/global/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (~/.config/yarn/global/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (~/.config/yarn/global/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (~/.config/yarn/global/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._settlePromise (~/.config/yarn/global/node_modules/bluebird/js/release/promise.js:580:21)
    at Promise._settlePromise0 (~/.config/yarn/global/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (~/.config/yarn/global/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (~/.config/yarn/global/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (~/.config/yarn/global/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (~/.config/yarn/global/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (~/.config/yarn/global/node_modules/bluebird/js/release/promise.js:567:18)
```

**Comment by alexisvincent** [comment]
Hi @johnbendi, `systems-config-builder` is still experimental and theres some cases it doesn't account for.

I've just published a new version of `systemjs-tools` which has the more up to date code. Try reinstalling `yarn global add systemjs-tools`.

This probably won't fix your error, but it will allow me to see where the error is.

Also, if you still get the error, it would really help me if you were able to submit a failing test case to `systems-config-builder`. It probably would only need the package.json that causes issues...

**Comment by johnbendi** [comment]
@alexisvincent thanks for the update. The error does go away with a new message `No cache, parsing node_modules. Warning this may take a while.` And then takes a long while to create the `generated.config.js` in my case the size is about `710K`. Is this how it's supposed to work. I am bit confused with that size and the length of time it takes to generate that file. Will it take the same amount of time when I need to update it again. Sorry for asking support questions here.

**Comment by alexisvincent** [comment]
When there's no cache it will take a while. If you run the generate step again it will be super quick. 

The output file as of now is unoptimized, it shouldn't be too different in size to the jspm config files.

If you want you can run it through a minifier to make the output smaller.

I'll turn this issue into an issue to provide optimised results via a cli flag

**Comment by johnbendi** [comment]
Thanks a lot @alexisvincent . I think it's okay to close this issue and open the `optimize results` issue,
